### ISSUE TITLE
Feature Request: Minimal AWS Infrastructure for ECS-Based Ingestion Service

### ISSUE THREAD

**Issue by ymohanty** [Data-Policy-and-Innovation-Centre/grievance#33]
### Problem

We need a minimal AWS infrastructure to run the grievance ingestion service on ECS, with scheduling handled by Prefect or the Python `schedule` package rather than AWS EventBridge. The focus should be on simplicity and minimal AWS dependencies.

### Proposed Solution

Implement a minimal Terraform infrastructure that provides:
- ECS cluster with Fargate for running the ingestion container
- ECR repository for container images
- IAM roles with proper permissions
- Security groups for network access
- Secrets management for sensitive configuration

**Scheduling will be handled by the application itself** using either:
- **Option A**: Prefect flows with scheduling
- **Option B**: Python `schedule` package with continuous container

#### Core AWS Resources
1. **ECS Cluster**: Fargate-based cluster for running ingestion containers
2. **ECR Repository**: Container registry for ingestion images
3. **IAM Roles**: Execution and task roles with minimal required permissions
4. **Task Definition**: Container definition with environment variables and secrets
5. **Security Groups**: Basic network security for external API access

#### Non-AWS Components (Application-Level)
1. **Scheduling**: Prefect flows or Python `schedule` package
2. **Logging**: Loguru with file output (CloudWatch integration later)
3. **Database**: External PostgreSQL/RDS (not managed by this Terraform)
4. **Monitoring**: Application-level health checks and metrics

#### Phase 1: Minimal ECS Setup
```hcl
# ECS Cluster
resource "aws_ecs_cluster" "grievance_ingestion" {
  name = "grievance-ingestion-cluster"
}

# ECR Repository
resource "aws_ecr_repository" "ingestion" {
  name = "grievance-ingestion"
}

# ECS Task Definition
resource "aws_ecs_task_definition" "ingestion" {
  family                   = "grievance-ingestion"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = var.task_cpu
  memory                   = var.task_memory
  execution_role_arn       = aws_iam_role.ecs_execution_role.arn
  task_role_arn           = aws_iam_role.ingestion_task_role.arn

  container_definitions = jsonencode([
    {
      name  = "ingestion"
      image = "${aws_ecr_repository.ingestion.repository_url}:latest"
      environment = [
        { name = "ENV", value = var.environment },
        { name = "AWS_REGION", value = var.aws_region }
      ]
      secrets = [
        { name = "DB_URL", valueFrom = aws_secretsmanager_secret.db_url.arn },
        { name = "JANASUNANI_API_USERNAME", valueFrom = aws_secretsmanager_secret.api_username.arn },
        { name = "JANASUNANI_API_PASSWORD", valueFrom = aws_secretsmanager_secret.api_password.arn }
      ]
    }
  ])
}

# ECS Service (continuous running)
resource "aws_ecs_service" "ingestion" {
  name            = "grievance-ingestion-service"
  cluster         = aws_ecs_cluster.grievance_ingestion.id
  task_definition = aws_ecs_task_definition.ingestion.arn
  desired_count   = 1  # Keep 1 instance running for scheduling
  
  network_configuration {
    subnets          = var.subnet_ids
    security_groups  = [aws_security_group.ingestion.id]
    assign_public_ip = true  # For external API access
  }
}
```

#### IAM Permissions
```hcl
# Execution Role (ECS system permissions)
resource "aws_iam_role_policy_attachment" "ecs_execution_role_policy" {
  role       = aws_iam_role.ecs_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# Task Role (application permissions)
resource "aws_iam_policy" "ingestion_task_policy" {
  name = "grievance-ingestion-task-policy"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue"
        ]
        Resource = [
          aws_secretsmanager_secret.db_url.arn,
          aws_secretsmanager_secret.api_username.arn,
          aws_secretsmanager_secret.api_password.arn
        ]
      }
    ]
  })
}
```

#### Option A: Prefect Integration
```python
# In orchestrator.py
from prefect import flow, task

@flow(name="grievance-ingestion")
def grievance_ingestion_flow():
    # Your existing ingestion logic here
    pass

if __name__ == "__main__":
    # Run the flow
    grievance_ingestion_flow()
```

#### Option B: Python Schedule Package
```python
# In orchestrator.py
import schedule
import time

def run_ingestion_job():
    # Your existing ingestion logic here
    pass

if __name__ == "__main__":
    # Schedule daily at 2 AM
    schedule.every().day.at("02:00").do(run_ingestion_job)
    
    # Run immediately on startup
    run_ingestion_job()
    
    # Keep running
    while True:
        schedule.run_pending()
        time.sleep(60)
```

#### Variables (variables.tf)
```hcl
variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "ap-south-1"
}

variable "task_cpu" {
  description = "CPU units for ECS task"
  type        = number
  default     = 1024
}

variable "task_memory" {
  description = "Memory for ECS task"
  type        = number
  default     = 2048
}

variable "vpc_id" {
  description = "VPC ID for security groups"
  type        = string
}

variable "subnet_ids" {
  description = "Subnet IDs for ECS service"
  type        = list(string)
}
```

### Acceptance Criteria

- [x] Create ECS cluster with Fargate launch type
- [x] Set up ECR repository for container images
- [x] Implement IAM roles with minimal required permissions
- [x] Create ECS task definition with container configuration
- [x] Add security groups for external API access
- [ ] Set up AWS Secrets Manager for sensitive configuration
- [x] Integrate with existing CI/CD pipeline
- [ ] Choose and implement application-level scheduling (Prefect or schedule)
- [ ] Test infrastructure deployment end-to-end
- [ ] Document deployment and maintenance procedures

### Additional Considerations

1. **Scheduling Choice**: Prefect vs Python schedule package
2. **Logging Strategy**: Loguru file output with future CloudWatch integration
3. **Health Checks**: Application-level health monitoring
4. **Cost Optimization**: Right-size ECS resources
5. **Security**: Least privilege access and secrets management
6. **Monitoring**: Basic application metrics and logging

### Expected Benefits

- **Minimal AWS Dependencies**: Only ECS for container orchestration
- **Simplicity**: Easy to understand and maintain infrastructure
- **Cost Efficiency**: Minimal AWS resources and services
- **Flexibility**: Application-level control over scheduling and logic
- **Scalability**: Easy to scale ECS tasks as needed
- **Security**: Proper IAM roles and secrets management

---

**Priority**: High  
**Estimated Effort**: 1-2 days  
**Related Files**: `backend/Dockerfile.ingestion`, `backend/app/ingestion/orchestrator.py`, `.github/workflows/`, `terraform/`

**Comment by ymohanty** [comment]
# Test Current Terraform Boilerplate & Setup GitHub Actions Deployment

Assigned: @nshaff3r 

I'll share the credentials you need via an ENV file 

## 🎯 **Objective**
Verify the current Terraform boilerplate on branch `aws` works as expected and automate deployment using GitHub Actions.

## 📋 **Current Infrastructure (Ready to Test)**
✅ **Completed:**
- VPC with public/private subnets
- RDS PostgreSQL database (t3.micro, 20GB)
- ECS Cluster (Fargate)
- ECR Repository for ingestion
- EventBridge weekly scheduling (every 7 days)
- CloudWatch logging
- IAM roles and security groups
- **NEW:** S3 bucket for document storage

## 🚀 **Tasks to Complete**

### **Phase 1: Add S3 Document Storage**
- [ ] Add S3 bucket resource to `main.tf`
- [ ] Add S3 environment variable to ECS task definition
- [ ] Add S3 permissions to ECS task role
- [ ] Update variables and outputs

### **Phase 2: Test Current Infrastructure**
- [ ] Deploy infrastructure using Terraform
- [ ] Build and push Docker image to ECR
- [ ] Verify EventBridge triggers ECS task
- [ ] Test database connectivity
- [ ] Verify CloudWatch logging works
- [ ] Test S3 bucket access

### **Phase 3: GitHub Actions Automation**
- [ ] Create GitHub Actions workflow for deployment
- [ ] Add secrets for AWS credentials and database password
- [ ] Automate Terraform plan/apply
- [ ] Automate Docker build and push
- [ ] Add infrastructure testing steps

## 🔧 **S3 Bucket Addition**

Add to `main.tf`:
```hcl
# S3 bucket for documents
resource "aws_s3_bucket" "documents" {
  bucket = "grievance-documents-${var.environment}"
  
  tags = {
    Name        = "Grievance Documents"
    Environment = var.environment
  }
}

# S3 bucket versioning
resource "aws_s3_bucket_versioning" "documents" {
  bucket = aws_s3_bucket.documents.id
  versioning_configuration {
    status = "Enabled"
  }
}
```

Update ECS task definition to include:
```hcl
environment = [
  {
    name  = "AWS_S3_DOCUMENTS"
    value = aws_s3_bucket.documents.bucket
  }
]
```

## 🧪 **Testing Checklist**

### **Infrastructure Testing:**
- [ ] `terraform plan` runs without errors
- [ ] `terraform apply` creates all resources
- [ ] RDS database is accessible
- [ ] ECS cluster is created
- [ ] ECR repository exists
- [ ] S3 bucket is created and accessible

### **Application Testing: Ingestion**
- [ ] Docker image builds successfully
- [ ] Image pushes to ECR without errors
- [ ] ECS task can pull image from ECR
- [ ] Container starts and runs
- [ ] Database connection works
- [ ] S3 access works
- [ ] Logs appear in CloudWatch

### **Scheduling Testing:**
- [ ] EventBridge rule is created
- [ ] Manual trigger of ECS task works
- [ ] Weekly schedule is configured correctly

## 📁 **GitHub Actions Workflow**

Create `.github/workflows/deploy.yml`:
```yaml
name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.dev.tfvars" -var="db_password=${{ secrets.DB_PASSWORD }}"
        working-directory: ./terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.dev.tfvars" -var="db_password=${{ secrets.DB_PASSWORD }}"
        working-directory: ./terraform
      - name: Build and Push Docker Image
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com
          docker build -f backend/Dockerfile.ingestion -t grievance-ingestion-dev:latest backend
          docker tag grievance-ingestion-dev:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/grievance-ingestion-dev:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/grievance-ingestion-dev:latest
```

## 🔑 **Required GitHub Secrets**

Add these secrets to your repository:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_ACCOUNT_ID`
- `DB_PASSWORD`

## ✅ **Success Criteria**

- [ ] Infrastructure deploys successfully via Terraform
- [ ] Docker image builds and pushes to ECR
- [ ] ECS task runs and connects to database
- [ ] S3 bucket is accessible from ECS
- [ ] GitHub Actions workflow completes successfully
- [ ] Weekly scheduling works as expected
- [ ] All logs appear in CloudWatch

## 📝 **Notes**

- Current cost: ~$23/month + S3 (~$1-5/month)
- Focus on testing existing infrastructure before adding features
- Keep deployment simple and automated
